graph LR
classDef person fill:#f9f,stroke:#333,stroke-width:2px;
classDef place fill:#ccf,stroke:#333,stroke-width:2px;
classDef bio fill:#cfc,stroke:#333,stroke-width:2px;
classDef concept fill:#fcf,stroke:#333,stroke-width:2px;
classDef state fill:#ffc,stroke:#333,stroke-width:2px;
classDef subject fill:#cff,stroke:#333,stroke-width:2px;
classDef metaphor fill:#fcc,stroke:#333,stroke-width:2px;
  概念_道(道)
  class 概念_道 concept;
  概念_德(德)
  class 概念_德 concept;
  主体_圣人(圣人)
  class 主体_圣人 subject;
  概念_无为(无为)
  class 概念_无为 concept;
  对立_有|无(有|无)
  class 对立_有|无 concept;
  主体_天地(天地)
  class 主体_天地 subject;
  主体_万物(万物)
  class 主体_万物 subject;
  主体_天(天)
  class 主体_天 subject;
  意象_器(器)
  class 意象_器 metaphor;
  意象_朴(朴)
  class 意象_朴 metaphor;
  主体_地(地)
  class 主体_地 subject;
  概念_自然(自然)
  class 概念_自然 concept;
  概念_名(名)
  class 概念_名 concept;
  境界_玄(玄)
  class 境界_玄 state;
  对立_美|恶(美|恶)
  class 对立_美|恶 concept;
  对立_善|不善(善|不善)
  class 对立_善|不善 concept;
  意象_水(水)
  class 意象_水 metaphor;
  意象_婴儿(婴儿)
  class 意象_婴儿 metaphor;
  概念_玄德(玄德)
  class 概念_玄德 concept;
  意象_谷(谷)
  class 意象_谷 metaphor;
  境界_恍惚(恍惚)
  class 境界_恍惚 state;
  主体_侯王(侯王)
  class 主体_侯王 subject;
  境界_无名(无名)
  class 境界_无名 state;
  境界_有名(有名)
  class 境界_有名 state;
  境界_妙(妙)
  class 境界_妙 state;
  意象_刍狗(刍狗)
  class 意象_刍狗 metaphor;
  意象_玄牝(玄牝)
  class 意象_玄牝 metaphor;
  概念_无物(无物)
  class 概念_无物 concept;
  境界_静(静)
  class 境界_静 state;
  对立_雄|雌(雄|雌)
  class 对立_雄|雌 concept;
  意象_溪(溪)
  class 意象_溪 metaphor;
  对立_白|黑(白|黑)
  class 对立_白|黑 concept;
  对立_荣|辱(荣|辱)
  class 对立_荣|辱 concept;
  意象_牝(牝)
  class 意象_牝 metaphor;
  境界_无欲(无欲)
  class 境界_无欲 state;
  境界_有欲(有欲)
  class 境界_有欲 state;
  境界_徼(徼)
  class 境界_徼 state;
  对立_难|易(难|易)
  class 对立_难|易 concept;
  对立_长|短(长|短)
  class 对立_长|短 concept;
  对立_高|下(高|下)
  class 对立_高|下 concept;
  对立_音|声(音|声)
  class 对立_音|声 concept;
  对立_前|后(前|后)
  class 对立_前|后 concept;
  境界_不言(不言)
  class 境界_不言 state;
  境界_无知无欲(无知无欲)
  class 境界_无知无欲 state;
  意象_尘(尘)
  class 意象_尘 metaphor;
  意象_橐龠(橐龠)
  class 意象_橐龠 metaphor;
  概念_中(中)
  class 概念_中 concept;
  主体_谷神(谷神)
  class 主体_谷神 subject;
  意象_金玉(金玉)
  class 意象_金玉 metaphor;
  境界_玄览(玄览)
  class 境界_玄览 state;
  主体_圣人 --- 概念_无为
  概念_无为 --- 概念_道
  主体_圣人 --- 概念_道
  主体_圣人 --- 概念_自然
  概念_自然 --- 概念_道
