graph LR
classDef concept fill:#fcf,stroke:#333,stroke-width:2px;
classDef state fill:#ffc,stroke:#333,stroke-width:2px;
classDef subject fill:#cff,stroke:#333,stroke-width:2px;
  concept_能(能)
  主体_人(人)
  class 主体_人 subject;
  subject_人(人)
  concept_道(道)
  concept_之(之)
  state_常清静(常清静)
  主体_心(心)
  class 主体_心 subject;
  境界_静(静)
  class 境界_静 state;
  state_悉皆(悉皆)
  concept_无为(无为)
  concept_自然(自然)
  concept_不(不)
  概念_欲(欲)
  class 概念_欲 concept;
  概念_神(神)
  class 概念_神 concept;
  境界_清(清)
  class 境界_清 state;
  concept_动(动)
  concept_静(静)
  concept_用(用)
  concept_体(体)
  concept_无(无)
  概念_大道(大道)
  class 概念_大道 concept;
  概念_道(道)
  class 概念_道 concept;
  概念_心(心)
  class 概念_心 concept;
  概念_六欲(六欲)
  class 概念_六欲 concept;
  概念_三毒(三毒)
  class 概念_三毒 concept;
  concept_本(本)
  concept_鬼神(鬼神)
  concept_生死(生死)
  concept_清静(清静)
  concept_大道(大道)
