graph LR
classDef person fill:#f9f,stroke:#333,stroke-width:2px;
classDef place fill:#ccf,stroke:#333,stroke-width:2px;
classDef bio fill:#cfc,stroke:#333,stroke-width:2px;
classDef concept fill:#fcf,stroke:#333,stroke-width:2px;
classDef state fill:#ffc,stroke:#333,stroke-width:2px;
classDef metaphor fill:#cff,stroke:#333,stroke-width:2px;
classDef subject fill:#fdd,stroke:#333,stroke-width:2px;
classDef duality fill:#ddd,stroke:#333,stroke-width:2px;
  主体_人(人)
  class 主体_人 subject;
  概念_能(能)
  class 概念_能 concept;
  概念_道(道)
  class 概念_道 concept;
  概念_之(之)
  class 概念_之 concept;
  境界_清静(清静)
  class 境界_清静 state;
  境界_悉皆(悉皆)
  class 境界_悉皆 state;
  概念_大道(大道)
  class 概念_大道 concept;
  主体_天地(天地)
  class 主体_天地 subject;
  主体_心(心)
  class 主体_心 subject;
  境界_静(静)
  class 境界_静 state;
  概念_无为(无为)
  class 概念_无为 concept;
  概念_自然(自然)
  class 概念_自然 concept;
  概念_不(不)
  class 概念_不 concept;
  主体_万物(万物)
  class 主体_万物 subject;
  概念_欲(欲)
  class 概念_欲 concept;
  概念_神(神)
  class 概念_神 concept;
  境界_清(清)
  class 境界_清 state;
  概念_动(动)
  class 概念_动 concept;
  概念_静(静)
  class 概念_静 concept;
  概念_用(用)
  class 概念_用 concept;
  概念_体(体)
  class 概念_体 concept;
  概念_无(无)
  class 概念_无 concept;
  概念_心(心)
  class 概念_心 concept;
  概念_六欲(六欲)
  class 概念_六欲 concept;
  概念_三毒(三毒)
  class 概念_三毒 concept;
  概念_本(本)
  class 概念_本 concept;
  主体_鬼神(鬼神)
  class 主体_鬼神 subject;
  概念_生死(生死)
  class 概念_生死 concept;
  概念_清静(清静)
  class 概念_清静 concept;
  境界_名(名)
  class 境界_名 state;
  境界_得道(得道)
  class 境界_得道 state;
  境界_不能(不能)
  class 境界_不能 state;
  概念_虚(虚)
  class 概念_虚 concept;
  概念_冲(冲)
  class 概念_冲 concept;
  境界_真人(真人)
  class 境界_真人 state;
  概念_与(与)
  class 概念_与 concept;
  概念_同(同)
  class 概念_同 concept;
  概念_而(而)
  class 概念_而 concept;
  主体_老君(老君)
  class 主体_老君 subject;
  概念_形(形)
  class 概念_形 concept;
