graph LR
classDef person fill:#f9f,stroke:#333,stroke-width:2px;
classDef place fill:#ccf,stroke:#333,stroke-width:2px;
classDef bio fill:#cfc,stroke:#333,stroke-width:2px;
classDef concept fill:#fcf,stroke:#333,stroke-width:2px;
classDef state fill:#ffc,stroke:#333,stroke-width:2px;
classDef subject fill:#cff,stroke:#333,stroke-width:2px;
classDef metaphor fill:#fcc,stroke:#333,stroke-width:2px;
  人物_老子(老子)
  class 人物_老子 person;
  主体_天地(天地)
  class 主体_天地 subject;
  境界_真人(真人)
  class 境界_真人 state;
  概念_自然(自然)
  class 概念_自然 concept;
  境界_至人(至人)
  class 境界_至人 state;
  境界_有名(有名)
  class 境界_有名 state;
  人物_孔子(孔子)
  class 人物_孔子 person;
  概念_物化(物化)
  class 概念_物化 concept;
  概念_玄德(玄德)
  class 概念_玄德 concept;
  人物_老聃(老聃)
  class 人物_老聃 person;
  概念_有待(有待)
  class 概念_有待 concept;
  人物_百里奚(百里奚)
  class 人物_百里奚 person;
  人物_老子 --- 概念_自然
  主体_天地 --- 人物_老子
  主体_天地 --- 概念_自然
  人物_老子 --- 境界_至人
  主体_天地 --- 境界_至人
  境界_有名 --- 概念_物化
  境界_有名 --- 概念_有待
  人物_老子 --- 境界_有名
  境界_有名 --- 境界_至人
  境界_有名 --- 概念_自然
  境界_有名 --- 概念_玄德
  主体_天地 --- 境界_有名
  人物_孔子 --- 境界_有名
  境界_有名 --- 境界_真人
  概念_有待 --- 概念_物化
  人物_老子 --- 概念_物化
  境界_至人 --- 概念_物化
  概念_物化 --- 概念_自然
  主体_天地 --- 概念_物化
  人物_孔子 --- 概念_物化
  境界_真人 --- 概念_物化
  人物_老子 --- 概念_有待
  境界_至人 --- 概念_有待
  概念_有待 --- 概念_自然
  主体_天地 --- 概念_有待
  人物_孔子 --- 概念_有待
  境界_真人 --- 概念_有待
  人物_老子 --- 概念_玄德
  人物_孔子 --- 人物_老子
  人物_老子 --- 境界_真人
  境界_至人 --- 概念_自然
  境界_至人 --- 概念_玄德
  人物_孔子 --- 境界_至人
  境界_真人 --- 境界_至人
  概念_玄德 --- 概念_自然
  人物_孔子 --- 概念_自然
  境界_真人 --- 概念_自然
  主体_天地 --- 概念_玄德
  人物_孔子 --- 概念_玄德
  境界_真人 --- 概念_玄德
  主体_天地 --- 人物_孔子
  主体_天地 --- 境界_真人
  人物_孔子 --- 境界_真人
  人物_百里奚 --- 境界_有名
  人物_老聃 --- 境界_有名
  人物_百里奚 --- 概念_自然
  人物_百里奚 --- 人物_老子
  人物_百里奚 --- 概念_玄德
  人物_百里奚 --- 人物_老聃
  主体_天地 --- 人物_百里奚
  人物_孔子 --- 人物_百里奚
  人物_老聃 --- 概念_自然
  人物_老子 --- 人物_老聃
  人物_老聃 --- 境界_至人
  人物_老聃 --- 概念_玄德
  主体_天地 --- 人物_老聃
  人物_孔子 --- 人物_老聃
  人物_老聃 --- 境界_真人
