graph LR
classDef person fill:#f9f,stroke:#333,stroke-width:2px;
classDef place fill:#ccf,stroke:#333,stroke-width:2px;
classDef bio fill:#cfc,stroke:#333,stroke-width:2px;
classDef concept fill:#fcf,stroke:#333,stroke-width:2px;
classDef state fill:#ffc,stroke:#333,stroke-width:2px;
classDef metaphor fill:#cff,stroke:#333,stroke-width:2px;
classDef subject fill:#fdd,stroke:#333,stroke-width:2px;
classDef duality fill:#ddd,stroke:#333,stroke-width:2px;
  主体_天(天)
  class 主体_天 subject;
  主体_人(人)
  class 主体_人 subject;
  主体_天地(天地)
  class 主体_天地 subject;
  主体_万物(万物)
  class 主体_万物 subject;
  概念_盗(盗)
  class 概念_盗 concept;
  概念_道(道)
  class 概念_道 concept;
  主体_地(地)
  class 主体_地 subject;
  概念_物(物)
  class 概念_物 concept;
  概念_五行(五行)
  class 概念_五行 concept;
  概念_万物(万物)
  class 概念_万物 concept;
  概念_阴阳(阴阳)
  class 概念_阴阳 concept;
  主体_心(心)
  class 主体_心 subject;
  概念_恩(恩)
  class 概念_恩 concept;
  概念_害(害)
  class 概念_害 concept;
  概念_知(知)
  class 概念_知 concept;
  概念_五事(五事)
  class 概念_五事 concept;
  概念_不善(不善)
  class 概念_不善 concept;
  概念_四时(四时)
  class 概念_四时 concept;
  概念_四方(四方)
  class 概念_四方 concept;
  概念_自然(自然)
  class 概念_自然 concept;
  概念_法(法)
  class 概念_法 concept;
  概念_机(机)
  class 概念_机 concept;
  概念_五贼(五贼)
  class 概念_五贼 concept;
  概念_五机(五机)
  class 概念_五机 concept;
  境界_神(神)
  class 境界_神 state;
  概念_利(利)
  class 概念_利 concept;
  概念_师(师)
  class 概念_师 concept;
  概念_圣(圣)
  class 概念_圣 concept;
  概念_不知(不知)
  class 概念_不知 concept;
  概念_执(执)
  class 概念_执 concept;
  概念_载(载)
  class 概念_载 concept;
  概念_动(动)
  class 概念_动 concept;
  概念_善(善)
  class 概念_善 concept;
  概念_三才(三才)
  class 概念_三才 concept;
  概念_无为(无为)
  class 概念_无为 concept;
  主体_黄帝(黄帝)
  class 主体_黄帝 subject;
  概念_阴符(阴符)
  class 概念_阴符 concept;
  概念_贼(贼)
  class 概念_贼 concept;
  境界_长生(长生)
  class 境界_长生 state;
  境界_长存(长存)
  class 境界_长存 state;
