graph LR
classDef person fill:#f9f,stroke:#333,stroke-width:2px;
classDef place fill:#ccf,stroke:#333,stroke-width:2px;
classDef bio fill:#cfc,stroke:#333,stroke-width:2px;
classDef concept fill:#fcf,stroke:#333,stroke-width:2px;
classDef state fill:#ffc,stroke:#333,stroke-width:2px;
  概念_名(名)
  class 概念_名 concept;
  概念_天(天)
  class 概念_天 concept;
  概念_地(地)
  class 概念_地 concept;
  概念_道(道)
  class 概念_道 concept;
  概念_知(知)
  class 概念_知 concept;
  概念_德(德)
  class 概念_德 concept;
  概念_神(神)
  class 概念_神 concept;
  概念_自然(自然)
  class 概念_自然 concept;
  人物_列子(列子)
  class 人物_列子 person;
  人物_孔子(孔子)
  class 人物_孔子 person;
  人物_老子(老子)
  class 人物_老子 person;
  概念_息(息)
  class 概念_息 concept;
  人物_舜(舜)
  class 人物_舜 person;
  生物_牛(牛)
  class 生物_牛 bio;
  人物_仲尼(仲尼)
  class 人物_仲尼 person;
  境界_至人(至人)
  class 境界_至人 state;
  人物_禹(禹)
  class 人物_禹 person;
  人物_惠施(惠施)
  class 人物_惠施 person;
  人物_文王(文王)
  class 人物_文王 person;
  人物_老聃(老聃)
  class 人物_老聃 person;
  生物_虎(虎)
  class 生物_虎 bio;
  人物_惠子(惠子)
  class 人物_惠子 person;
  生物_狙(狙)
  class 生物_狙 bio;
  生物_山木(山木)
  class 生物_山木 bio;
  生物_蜩(蜩)
  class 生物_蜩 bio;
  境界_真人(真人)
  class 境界_真人 state;
  生物_豹(豹)
  class 生物_豹 bio;
  概念_物化(物化)
  class 概念_物化 concept;
  人物_周公(周公)
  class 人物_周公 person;
  生物_鹿(鹿)
  class 生物_鹿 bio;
  人物_武王(武王)
  class 人物_武王 person;
  人物_肩吾(肩吾)
  class 人物_肩吾 person;
  境界_坐忘(坐忘)
  class 境界_坐忘 state;
  生物_芧(芧)
  class 生物_芧 bio;
  概念_有待(有待)
  class 概念_有待 concept;
  生物_猿(猿)
  class 生物_猿 bio;
  生物_桂(桂)
  class 生物_桂 bio;
  人物_墨者(墨者)
  class 人物_墨者 person;
  人物_王倪(王倪)
  class 人物_王倪 person;
  人物_匠石(匠石)
  class 人物_匠石 person;
  人物_列子 --- 概念_息
  概念_息 --- 生物_蜩
  人物_列子 --- 生物_蜩
  人物_王倪 --- 境界_至人
  境界_至人 --- 概念_物化
  人物_禹 --- 境界_至人
  人物_舜 --- 境界_至人
  境界_至人 --- 概念_道
  人物_王倪 --- 概念_物化
  人物_王倪 --- 人物_禹
  人物_王倪 --- 人物_舜
  人物_王倪 --- 概念_道
  人物_禹 --- 概念_物化
  人物_舜 --- 概念_物化
  概念_物化 --- 概念_道
  人物_禹 --- 人物_舜
  人物_禹 --- 概念_道
  人物_舜 --- 概念_道
  概念_道 --- 生物_牛
  概念_知 --- 生物_牛
  人物_老聃 --- 生物_牛
  概念_知 --- 概念_道
  人物_老聃 --- 概念_道
  人物_老聃 --- 概念_知
  境界_至人 --- 生物_山木
  境界_至人 --- 生物_桂
  人物_匠石 --- 境界_至人
  人物_孔子 --- 境界_至人
  人物_仲尼 --- 境界_至人
  生物_山木 --- 生物_桂
  人物_匠石 --- 生物_山木
  概念_道 --- 生物_山木
  人物_舜 --- 生物_山木
  人物_禹 --- 生物_山木
  人物_孔子 --- 生物_山木
  人物_仲尼 --- 生物_山木
  概念_道 --- 生物_桂
  人物_舜 --- 生物_桂
  人物_禹 --- 生物_桂
  人物_孔子 --- 生物_桂
  人物_仲尼 --- 生物_桂
  人物_匠石 --- 概念_道
  人物_匠石 --- 人物_舜
  人物_匠石 --- 人物_禹
  人物_匠石 --- 人物_孔子
  人物_仲尼 --- 人物_匠石
  人物_孔子 --- 概念_道
  人物_仲尼 --- 概念_道
  人物_孔子 --- 人物_舜
  人物_仲尼 --- 人物_舜
  人物_孔子 --- 人物_禹
  人物_仲尼 --- 人物_禹
  人物_仲尼 --- 人物_孔子
  概念_名 --- 概念_天
  概念_名 --- 概念_神
  概念_名 --- 概念_自然
  人物_舜 --- 概念_名
  概念_名 --- 概念_物化
  人物_仲尼 --- 概念_名
  人物_孔子 --- 概念_名
  境界_至人 --- 概念_名
  概念_名 --- 概念_道
  概念_名 --- 概念_地
  概念_名 --- 概念_德
  概念_名 --- 概念_知
  概念_名 --- 概念_息
  概念_天 --- 概念_神
  概念_天 --- 概念_自然
  人物_舜 --- 概念_天
  概念_天 --- 概念_物化
  人物_仲尼 --- 概念_天
  人物_孔子 --- 概念_天
  境界_至人 --- 概念_天
  概念_天 --- 概念_道
  概念_地 --- 概念_天
  概念_天 --- 概念_德
  概念_天 --- 概念_知
  概念_天 --- 概念_息
  概念_神 --- 概念_自然
  人物_舜 --- 概念_神
  概念_物化 --- 概念_神
  人物_仲尼 --- 概念_神
  人物_孔子 --- 概念_神
  境界_至人 --- 概念_神
  概念_神 --- 概念_道
  概念_地 --- 概念_神
  概念_德 --- 概念_神
  概念_知 --- 概念_神
  概念_息 --- 概念_神
  人物_舜 --- 概念_自然
  概念_物化 --- 概念_自然
  人物_仲尼 --- 概念_自然
  人物_孔子 --- 概念_自然
  境界_至人 --- 概念_自然
  概念_自然 --- 概念_道
  概念_地 --- 概念_自然
  概念_德 --- 概念_自然
  概念_知 --- 概念_自然
  概念_息 --- 概念_自然
  人物_舜 --- 概念_地
  人物_舜 --- 概念_德
  人物_舜 --- 概念_知
  人物_舜 --- 概念_息
  人物_仲尼 --- 概念_物化
  人物_孔子 --- 概念_物化
  概念_地 --- 概念_物化
  概念_德 --- 概念_物化
  概念_物化 --- 概念_知
  概念_息 --- 概念_物化
  人物_仲尼 --- 概念_地
  人物_仲尼 --- 概念_德
  人物_仲尼 --- 概念_知
  人物_仲尼 --- 概念_息
  人物_孔子 --- 概念_地
  人物_孔子 --- 概念_德
  人物_孔子 --- 概念_知
  人物_孔子 --- 概念_息
  境界_至人 --- 概念_地
  境界_至人 --- 概念_德
  境界_至人 --- 概念_知
  境界_至人 --- 概念_息
  概念_地 --- 概念_道
  概念_德 --- 概念_道
  概念_息 --- 概念_道
  概念_地 --- 概念_德
  概念_地 --- 概念_知
  概念_地 --- 概念_息
  概念_德 --- 概念_知
  概念_德 --- 概念_息
  概念_息 --- 概念_知
  概念_名 --- 生物_豹
  境界_真人 --- 概念_名
  概念_名 --- 生物_牛
  概念_名 --- 概念_有待
  人物_武王 --- 概念_名
  概念_名 --- 生物_桂
  境界_坐忘 --- 概念_名
  人物_禹 --- 概念_名
  人物_文王 --- 概念_名
  概念_名 --- 生物_虎
  人物_肩吾 --- 概念_名
  境界_真人 --- 生物_豹
  境界_至人 --- 生物_豹
  生物_牛 --- 生物_豹
  概念_德 --- 生物_豹
  概念_有待 --- 生物_豹
  概念_知 --- 生物_豹
  概念_息 --- 生物_豹
  概念_天 --- 生物_豹
  人物_武王 --- 生物_豹
  生物_桂 --- 生物_豹
  境界_坐忘 --- 生物_豹
  概念_地 --- 生物_豹
  概念_神 --- 生物_豹
  概念_自然 --- 生物_豹
  人物_舜 --- 生物_豹
  人物_禹 --- 生物_豹
  人物_仲尼 --- 生物_豹
  人物_文王 --- 生物_豹
  人物_孔子 --- 生物_豹
  生物_虎 --- 生物_豹
  概念_道 --- 生物_豹
  人物_肩吾 --- 生物_豹
  境界_真人 --- 境界_至人
  境界_真人 --- 生物_牛
  境界_真人 --- 概念_德
  境界_真人 --- 概念_有待
  境界_真人 --- 概念_知
  境界_真人 --- 概念_息
  境界_真人 --- 概念_天
  人物_武王 --- 境界_真人
  境界_坐忘 --- 境界_真人
  境界_真人 --- 概念_地
  境界_真人 --- 概念_神
  境界_真人 --- 概念_自然
  人物_舜 --- 境界_真人
  人物_禹 --- 境界_真人
  人物_仲尼 --- 境界_真人
  人物_文王 --- 境界_真人
  人物_孔子 --- 境界_真人
  境界_真人 --- 生物_虎
  境界_真人 --- 概念_道
  人物_肩吾 --- 境界_真人
  境界_至人 --- 生物_牛
  境界_至人 --- 概念_有待
  人物_武王 --- 境界_至人
  境界_坐忘 --- 境界_至人
  人物_文王 --- 境界_至人
  境界_至人 --- 生物_虎
  人物_肩吾 --- 境界_至人
  概念_德 --- 生物_牛
  概念_有待 --- 生物_牛
  概念_息 --- 生物_牛
  概念_天 --- 生物_牛
  人物_武王 --- 生物_牛
  生物_桂 --- 生物_牛
  境界_坐忘 --- 生物_牛
  概念_地 --- 生物_牛
  概念_神 --- 生物_牛
  概念_自然 --- 生物_牛
  人物_舜 --- 生物_牛
  人物_禹 --- 生物_牛
  人物_仲尼 --- 生物_牛
  人物_文王 --- 生物_牛
  人物_孔子 --- 生物_牛
  生物_牛 --- 生物_虎
  人物_肩吾 --- 生物_牛
  概念_德 --- 概念_有待
  人物_武王 --- 概念_德
  概念_德 --- 生物_桂
  境界_坐忘 --- 概念_德
  人物_禹 --- 概念_德
  人物_文王 --- 概念_德
  概念_德 --- 生物_虎
  人物_肩吾 --- 概念_德
  概念_有待 --- 概念_知
  概念_息 --- 概念_有待
  概念_天 --- 概念_有待
  境界_坐忘 --- 概念_有待
  概念_地 --- 概念_有待
  概念_有待 --- 概念_神
  概念_有待 --- 概念_自然
  人物_舜 --- 概念_有待
  人物_禹 --- 概念_有待
  人物_仲尼 --- 概念_有待
  人物_文王 --- 概念_有待
  人物_孔子 --- 概念_有待
  概念_有待 --- 生物_虎
  概念_有待 --- 概念_道
  人物_肩吾 --- 概念_有待
  人物_武王 --- 概念_知
  概念_知 --- 生物_桂
  境界_坐忘 --- 概念_知
  人物_禹 --- 概念_知
  人物_文王 --- 概念_知
  概念_知 --- 生物_虎
  人物_肩吾 --- 概念_知
  人物_武王 --- 概念_息
  概念_息 --- 生物_桂
  境界_坐忘 --- 概念_息
  人物_禹 --- 概念_息
  人物_文王 --- 概念_息
  概念_息 --- 生物_虎
  人物_肩吾 --- 概念_息
  人物_武王 --- 概念_天
  概念_天 --- 生物_桂
  境界_坐忘 --- 概念_天
  人物_禹 --- 概念_天
  人物_文王 --- 概念_天
  概念_天 --- 生物_虎
  人物_肩吾 --- 概念_天
  人物_武王 --- 生物_桂
  人物_武王 --- 境界_坐忘
  人物_武王 --- 概念_地
  人物_武王 --- 概念_神
  人物_武王 --- 概念_自然
  人物_武王 --- 人物_舜
  人物_武王 --- 人物_禹
  人物_仲尼 --- 人物_武王
  人物_文王 --- 人物_武王
  人物_孔子 --- 人物_武王
  人物_武王 --- 生物_虎
  人物_武王 --- 概念_道
  人物_武王 --- 人物_肩吾
  概念_地 --- 生物_桂
  概念_神 --- 生物_桂
  概念_自然 --- 生物_桂
  人物_文王 --- 生物_桂
  生物_桂 --- 生物_虎
  人物_肩吾 --- 生物_桂
  境界_坐忘 --- 概念_地
  境界_坐忘 --- 概念_神
  境界_坐忘 --- 概念_自然
  人物_舜 --- 境界_坐忘
  人物_禹 --- 境界_坐忘
  人物_仲尼 --- 境界_坐忘
  人物_文王 --- 境界_坐忘
  人物_孔子 --- 境界_坐忘
  境界_坐忘 --- 生物_虎
  境界_坐忘 --- 概念_道
  人物_肩吾 --- 境界_坐忘
  人物_禹 --- 概念_地
  人物_文王 --- 概念_地
  概念_地 --- 生物_虎
  人物_肩吾 --- 概念_地
  人物_禹 --- 概念_神
  人物_文王 --- 概念_神
  概念_神 --- 生物_虎
  人物_肩吾 --- 概念_神
  人物_禹 --- 概念_自然
  人物_文王 --- 概念_自然
  概念_自然 --- 生物_虎
  人物_肩吾 --- 概念_自然
  人物_文王 --- 人物_舜
  人物_舜 --- 生物_虎
  人物_肩吾 --- 人物_舜
  人物_文王 --- 人物_禹
  人物_禹 --- 生物_虎
  人物_禹 --- 人物_肩吾
  人物_仲尼 --- 人物_文王
  人物_仲尼 --- 生物_虎
  人物_仲尼 --- 人物_肩吾
  人物_孔子 --- 人物_文王
  人物_文王 --- 生物_虎
  人物_文王 --- 概念_道
  人物_文王 --- 人物_肩吾
  人物_孔子 --- 生物_虎
  人物_孔子 --- 人物_肩吾
  概念_道 --- 生物_虎
  人物_肩吾 --- 生物_虎
  人物_肩吾 --- 概念_道
  人物_老子 --- 概念_名
  概念_名 --- 生物_猿
  人物_列子 --- 概念_名
  人物_王倪 --- 概念_名
  人物_老聃 --- 概念_名
  概念_名 --- 生物_狙
  人物_老子 --- 生物_豹
  人物_老子 --- 生物_猿
  人物_老子 --- 境界_至人
  人物_老子 --- 生物_牛
  人物_老子 --- 概念_德
  人物_老子 --- 概念_知
  人物_老子 --- 概念_息
  人物_列子 --- 人物_老子
  人物_王倪 --- 人物_老子
  人物_老子 --- 概念_天
  人物_老子 --- 概念_物化
  人物_老子 --- 境界_坐忘
  人物_老子 --- 概念_地
  人物_老子 --- 概念_道
  人物_老子 --- 人物_老聃
  人物_老子 --- 概念_神
  人物_老子 --- 概念_自然
  人物_老子 --- 人物_舜
  人物_老子 --- 生物_虎
  人物_老子 --- 生物_狙
  人物_老子 --- 人物_肩吾
  生物_猿 --- 生物_豹
  人物_列子 --- 生物_豹
  人物_王倪 --- 生物_豹
  概念_物化 --- 生物_豹
  人物_老聃 --- 生物_豹
  生物_狙 --- 生物_豹
  境界_至人 --- 生物_猿
  生物_牛 --- 生物_猿
  概念_德 --- 生物_猿
  概念_知 --- 生物_猿
  概念_息 --- 生物_猿
  人物_列子 --- 生物_猿
  人物_王倪 --- 生物_猿
  概念_天 --- 生物_猿
  概念_物化 --- 生物_猿
  境界_坐忘 --- 生物_猿
  概念_地 --- 生物_猿
  概念_道 --- 生物_猿
  人物_老聃 --- 生物_猿
  概念_神 --- 生物_猿
  概念_自然 --- 生物_猿
  人物_舜 --- 生物_猿
  生物_猿 --- 生物_虎
  生物_狙 --- 生物_猿
  人物_列子 --- 境界_至人
  人物_老聃 --- 境界_至人
  境界_至人 --- 生物_狙
  人物_列子 --- 生物_牛
  人物_王倪 --- 生物_牛
  概念_物化 --- 生物_牛
  生物_牛 --- 生物_狙
  人物_列子 --- 概念_德
  人物_王倪 --- 概念_德
  人物_老聃 --- 概念_德
  概念_德 --- 生物_狙
  人物_列子 --- 概念_知
  人物_王倪 --- 概念_知
  概念_知 --- 生物_狙
  人物_王倪 --- 概念_息
  人物_老聃 --- 概念_息
  概念_息 --- 生物_狙
  人物_列子 --- 人物_王倪
  人物_列子 --- 概念_天
  人物_列子 --- 概念_物化
  人物_列子 --- 境界_坐忘
  人物_列子 --- 概念_地
  人物_列子 --- 概念_道
  人物_列子 --- 人物_老聃
  人物_列子 --- 概念_神
  人物_列子 --- 概念_自然
  人物_列子 --- 人物_舜
  人物_列子 --- 生物_虎
  人物_列子 --- 生物_狙
  人物_列子 --- 人物_肩吾
  人物_王倪 --- 概念_天
  人物_王倪 --- 境界_坐忘
  人物_王倪 --- 概念_地
  人物_王倪 --- 人物_老聃
  人物_王倪 --- 概念_神
  人物_王倪 --- 概念_自然
  人物_王倪 --- 生物_虎
  人物_王倪 --- 生物_狙
  人物_王倪 --- 人物_肩吾
  人物_老聃 --- 概念_天
  概念_天 --- 生物_狙
  境界_坐忘 --- 概念_物化
  人物_老聃 --- 概念_物化
  概念_物化 --- 生物_虎
  概念_物化 --- 生物_狙
  人物_肩吾 --- 概念_物化
  人物_老聃 --- 境界_坐忘
  境界_坐忘 --- 生物_狙
  人物_老聃 --- 概念_地
  概念_地 --- 生物_狙
  概念_道 --- 生物_狙
  人物_老聃 --- 概念_神
  人物_老聃 --- 概念_自然
  人物_老聃 --- 人物_舜
  人物_老聃 --- 生物_虎
  人物_老聃 --- 生物_狙
  人物_老聃 --- 人物_肩吾
  概念_神 --- 生物_狙
  概念_自然 --- 生物_狙
  人物_舜 --- 生物_狙
  生物_狙 --- 生物_虎
  人物_惠子 --- 概念_名
  概念_名 --- 生物_山木
  人物_惠施 --- 概念_名
  概念_名 --- 生物_芧
  人物_墨者 --- 概念_名
  概念_名 --- 生物_鹿
  概念_名 --- 生物_蜩
  人物_周公 --- 概念_名
  人物_惠子 --- 人物_老子
  人物_老子 --- 生物_山木
  人物_惠施 --- 人物_老子
  人物_老子 --- 生物_芧
  人物_老子 --- 概念_有待
  人物_墨者 --- 人物_老子
  人物_老子 --- 生物_鹿
  人物_老子 --- 生物_桂
  人物_武王 --- 人物_老子
  人物_老子 --- 生物_蜩
  人物_周公 --- 人物_老子
  人物_禹 --- 人物_老子
  人物_孔子 --- 人物_老子
  人物_文王 --- 人物_老子
  人物_仲尼 --- 人物_老子
  人物_惠子 --- 生物_豹
  生物_山木 --- 生物_豹
  人物_惠施 --- 生物_豹
  人物_墨者 --- 生物_豹
  生物_蜩 --- 生物_豹
  人物_周公 --- 生物_豹
  生物_猿 --- 生物_鹿
  人物_武王 --- 生物_猿
  人物_周公 --- 生物_猿
  人物_禹 --- 生物_猿
  人物_孔子 --- 生物_猿
  人物_文王 --- 生物_猿
  人物_仲尼 --- 生物_猿
  人物_惠子 --- 境界_至人
  人物_惠施 --- 境界_至人
  境界_至人 --- 生物_芧
  人物_墨者 --- 境界_至人
  境界_至人 --- 生物_鹿
  境界_至人 --- 生物_蜩
  人物_周公 --- 境界_至人
  人物_惠子 --- 生物_牛
  生物_山木 --- 生物_牛
  人物_惠施 --- 生物_牛
  生物_牛 --- 生物_芧
  人物_墨者 --- 生物_牛
  生物_牛 --- 生物_鹿
  生物_牛 --- 生物_蜩
  人物_周公 --- 生物_牛
  人物_惠子 --- 生物_山木
  人物_惠子 --- 人物_惠施
  人物_惠子 --- 概念_德
  人物_惠子 --- 生物_芧
  人物_惠子 --- 概念_知
  人物_惠子 --- 概念_息
  人物_列子 --- 人物_惠子
  人物_惠子 --- 概念_有待
  人物_墨者 --- 人物_惠子
  人物_惠子 --- 概念_天
  人物_惠子 --- 人物_武王
  人物_惠子 --- 概念_物化
  人物_惠子 --- 境界_坐忘
  人物_惠子 --- 概念_地
  人物_惠子 --- 概念_道
  人物_惠子 --- 人物_老聃
  人物_惠子 --- 生物_蜩
  人物_周公 --- 人物_惠子
  人物_惠子 --- 概念_神
  人物_惠子 --- 概念_自然
  人物_惠子 --- 人物_舜
  人物_惠子 --- 人物_禹
  人物_孔子 --- 人物_惠子
  人物_惠子 --- 人物_文王
  人物_惠子 --- 生物_虎
  人物_惠子 --- 生物_狙
  人物_仲尼 --- 人物_惠子
  人物_惠子 --- 人物_肩吾
  人物_惠施 --- 生物_山木
  概念_德 --- 生物_山木
  概念_知 --- 生物_山木
  概念_息 --- 生物_山木
  人物_列子 --- 生物_山木
  人物_墨者 --- 生物_山木
  概念_天 --- 生物_山木
  人物_武王 --- 生物_山木
  概念_物化 --- 生物_山木
  概念_地 --- 生物_山木
  人物_老聃 --- 生物_山木
  人物_周公 --- 生物_山木
  概念_神 --- 生物_山木
  概念_自然 --- 生物_山木
  人物_文王 --- 生物_山木
  生物_山木 --- 生物_虎
  人物_惠施 --- 概念_德
  人物_惠施 --- 生物_芧
  人物_惠施 --- 概念_知
  人物_惠施 --- 概念_息
  人物_列子 --- 人物_惠施
  人物_惠施 --- 概念_有待
  人物_墨者 --- 人物_惠施
  人物_惠施 --- 概念_天
  人物_惠施 --- 人物_武王
  人物_惠施 --- 概念_物化
  人物_惠施 --- 境界_坐忘
  人物_惠施 --- 概念_地
  人物_惠施 --- 概念_道
  人物_惠施 --- 人物_老聃
  人物_惠施 --- 生物_蜩
  人物_周公 --- 人物_惠施
  人物_惠施 --- 概念_神
  人物_惠施 --- 概念_自然
  人物_惠施 --- 人物_舜
  人物_惠施 --- 人物_禹
  人物_孔子 --- 人物_惠施
  人物_惠施 --- 人物_文王
  人物_惠施 --- 生物_虎
  人物_惠施 --- 生物_狙
  人物_仲尼 --- 人物_惠施
  人物_惠施 --- 人物_肩吾
  概念_德 --- 生物_芧
  人物_墨者 --- 概念_德
  概念_德 --- 生物_鹿
  概念_德 --- 生物_蜩
  人物_周公 --- 概念_德
  概念_知 --- 生物_芧
  概念_息 --- 生物_芧
  人物_列子 --- 生物_芧
  人物_墨者 --- 生物_芧
  概念_天 --- 生物_芧
  概念_地 --- 生物_芧
  概念_道 --- 生物_芧
  概念_神 --- 生物_芧
  概念_自然 --- 生物_芧
  人物_舜 --- 生物_芧
  人物_禹 --- 生物_芧
  生物_狙 --- 生物_芧
  人物_墨者 --- 概念_知
  概念_知 --- 生物_鹿
  概念_知 --- 生物_蜩
  人物_周公 --- 概念_知
  人物_墨者 --- 概念_息
  概念_息 --- 生物_鹿
  人物_周公 --- 概念_息
  人物_列子 --- 人物_墨者
  人物_列子 --- 生物_鹿
  人物_列子 --- 生物_桂
  人物_列子 --- 人物_武王
  人物_列子 --- 人物_周公
  人物_列子 --- 人物_禹
  人物_列子 --- 人物_孔子
  人物_列子 --- 人物_文王
  人物_仲尼 --- 人物_列子
  人物_墨者 --- 概念_有待
  人物_老聃 --- 概念_有待
  概念_有待 --- 生物_蜩
  人物_墨者 --- 生物_鹿
  人物_墨者 --- 概念_天
  人物_墨者 --- 生物_桂
  人物_墨者 --- 人物_武王
  人物_墨者 --- 概念_物化
  人物_墨者 --- 境界_坐忘
  人物_墨者 --- 概念_地
  人物_墨者 --- 概念_道
  人物_墨者 --- 人物_老聃
  人物_周公 --- 人物_墨者
  人物_墨者 --- 概念_神
  人物_墨者 --- 概念_自然
  人物_墨者 --- 人物_舜
  人物_墨者 --- 人物_禹
  人物_墨者 --- 人物_孔子
  人物_墨者 --- 人物_文王
  人物_墨者 --- 生物_虎
  人物_墨者 --- 生物_狙
  人物_仲尼 --- 人物_墨者
  人物_墨者 --- 人物_肩吾
  概念_天 --- 生物_鹿
  人物_武王 --- 生物_鹿
  概念_物化 --- 生物_鹿
  境界_坐忘 --- 生物_鹿
  概念_地 --- 生物_鹿
  概念_道 --- 生物_鹿
  人物_老聃 --- 生物_鹿
  人物_周公 --- 生物_鹿
  概念_神 --- 生物_鹿
  概念_自然 --- 生物_鹿
  人物_舜 --- 生物_鹿
  人物_禹 --- 生物_鹿
  人物_孔子 --- 生物_鹿
  人物_文王 --- 生物_鹿
  生物_虎 --- 生物_鹿
  生物_狙 --- 生物_鹿
  人物_仲尼 --- 生物_鹿
  人物_孔子 --- 人物_王倪
  人物_仲尼 --- 人物_王倪
  概念_天 --- 生物_蜩
  人物_周公 --- 概念_天
  人物_老聃 --- 生物_桂
  人物_周公 --- 生物_桂
  人物_武王 --- 概念_物化
  人物_武王 --- 人物_老聃
  人物_周公 --- 人物_武王
  人物_武王 --- 生物_狙
  人物_周公 --- 概念_物化
  人物_文王 --- 概念_物化
  人物_周公 --- 境界_坐忘
  概念_地 --- 生物_蜩
  人物_周公 --- 概念_地
  概念_道 --- 生物_蜩
  人物_周公 --- 概念_道
  人物_老聃 --- 生物_蜩
  人物_周公 --- 人物_老聃
  人物_禹 --- 人物_老聃
  人物_孔子 --- 人物_老聃
  人物_文王 --- 人物_老聃
  人物_仲尼 --- 人物_老聃
  人物_周公 --- 生物_蜩
  概念_神 --- 生物_蜩
  概念_自然 --- 生物_蜩
  人物_舜 --- 生物_蜩
  人物_禹 --- 生物_蜩
  人物_孔子 --- 生物_蜩
  生物_虎 --- 生物_蜩
  人物_仲尼 --- 生物_蜩
  人物_周公 --- 概念_神
  人物_周公 --- 概念_自然
  人物_周公 --- 人物_舜
  人物_周公 --- 人物_禹
  人物_周公 --- 人物_孔子
  人物_周公 --- 人物_文王
  人物_周公 --- 生物_虎
  人物_周公 --- 生物_狙
  人物_仲尼 --- 人物_周公
  人物_周公 --- 人物_肩吾
  人物_禹 --- 生物_狙
  人物_孔子 --- 生物_狙
  人物_文王 --- 生物_狙
  人物_仲尼 --- 生物_狙
  人物_老子 --- 境界_真人
  人物_惠子 --- 境界_真人
  人物_惠施 --- 境界_真人
  人物_列子 --- 境界_真人
  人物_墨者 --- 境界_真人
  境界_真人 --- 生物_狙
  境界_真人 --- 概念_物化
  人物_老聃 --- 境界_真人
  人物_周公 --- 境界_真人
