graph LR
classDef person fill:#f9f,stroke:#333,stroke-width:2px;
classDef place fill:#ccf,stroke:#333,stroke-width:2px;
classDef bio fill:#cfc,stroke:#333,stroke-width:2px;
classDef concept fill:#fcf,stroke:#333,stroke-width:2px;
classDef state fill:#ffc,stroke:#333,stroke-width:2px;
classDef metaphor fill:#cff,stroke:#333,stroke-width:2px;
classDef subject fill:#fdd,stroke:#333,stroke-width:2px;
classDef duality fill:#ddd,stroke:#333,stroke-width:2px;
  概念_大道(大道)
  class 概念_大道 concept;
  境界_得道(得道)
  class 境界_得道 state;
  主体_天地(天地)
  class 主体_天地 subject;
  境界_真人(真人)
  class 境界_真人 state;
  概念_不知(不知)
  class 概念_不知 concept;
  境界_悉皆(悉皆)
  class 境界_悉皆 state;
  概念_自然(自然)
  class 概念_自然 concept;
  概念_三毒(三毒)
  class 概念_三毒 concept;
  境界_不能(不能)
  class 境界_不能 state;
  概念_生死(生死)
  class 概念_生死 concept;
