graph LR
classDef person fill:#f9f,stroke:#333,stroke-width:2px;
classDef place fill:#ccf,stroke:#333,stroke-width:2px;
classDef bio fill:#cfc,stroke:#333,stroke-width:2px;
classDef concept fill:#fcf,stroke:#333,stroke-width:2px;
classDef state fill:#ffc,stroke:#333,stroke-width:2px;
classDef metaphor fill:#cff,stroke:#333,stroke-width:2px;
classDef subject fill:#fdd,stroke:#333,stroke-width:2px;
classDef duality fill:#ddd,stroke:#333,stroke-width:2px;
  境界_不能(不能)
  class 境界_不能 state;
  概念_不知(不知)
  class 概念_不知 concept;
  主体_天下(天下)
  class 主体_天下 subject;
  概念_自然(自然)
  class 概念_自然 concept;
  主体_天地(天地)
  class 主体_天地 subject;
  人物_仲尼(仲尼)
  class 人物_仲尼 person;
  主体_鬼神(鬼神)
  class 主体_鬼神 subject;
  人物_老子(老子)
  class 人物_老子 person;
  境界_得道(得道)
  class 境界_得道 state;
  人物_儒者(儒者)
  class 人物_儒者 person;
  生物_彭祖(彭祖)
  class 生物_彭祖 bio;
  境界_真人(真人)
  class 境界_真人 state;
  人物_周公(周公)
  class 人物_周公 person;
  概念_四方(四方)
  class 概念_四方 concept;
  境界_至人(至人)
  class 境界_至人 state;
  生物_朝菌(朝菌)
  class 生物_朝菌 bio;
  人物_孔子(孔子)
  class 人物_孔子 person;
  概念_五行(五行)
  class 概念_五行 concept;
  境界_有名(有名)
  class 境界_有名 state;
  概念_大道(大道)
  class 概念_大道 concept;
  人物_文王(文王)
  class 人物_文王 person;
  概念_物化(物化)
  class 概念_物化 concept;
  生物_大椿(大椿)
  class 生物_大椿 bio;
  概念_有待(有待)
  class 概念_有待 concept;
  人物_墨者(墨者)
  class 人物_墨者 person;
  人物_匠石(匠石)
  class 人物_匠石 person;
  人物_列子(列子)
  class 人物_列子 person;
  概念_生死(生死)
  class 概念_生死 concept;
  人物_武王(武王)
  class 人物_武王 person;
  概念_不善(不善)
  class 概念_不善 concept;
  人物_惠子(惠子)
  class 人物_惠子 person;
  概念_五事(五事)
  class 概念_五事 concept;
  境界_恍惚(恍惚)
  class 境界_恍惚 state;
  生物_蟪蛄(蟪蛄)
  class 生物_蟪蛄 bio;
  概念_玄德(玄德)
  class 概念_玄德 concept;
  人物_老聃(老聃)
  class 人物_老聃 person;
  概念_三才(三才)
  class 概念_三才 concept;
  人物_被衣(被衣)
  class 人物_被衣 person;
  人物_惠施(惠施)
  class 人物_惠施 person;
  境界_天池(天池)
  class 境界_天池 state;
  人物_仲尼 --- 生物_大椿
  境界_得道 --- 生物_大椿
  境界_真人 --- 生物_大椿
  人物_周公 --- 生物_大椿
  主体_天地 --- 生物_大椿
  概念_不知 --- 生物_大椿
  生物_大椿 --- 生物_朝菌
  境界_至人 --- 生物_大椿
  主体_鬼神 --- 生物_大椿
  主体_天下 --- 生物_大椿
  人物_儒者 --- 生物_大椿
  境界_不能 --- 生物_大椿
  概念_自然 --- 生物_大椿
  人物_仲尼 --- 人物_墨者
  人物_仲尼 --- 人物_武王
  人物_仲尼 --- 境界_得道
  人物_仲尼 --- 境界_真人
  人物_仲尼 --- 人物_老子
  人物_仲尼 --- 人物_周公
  人物_仲尼 --- 人物_孔子
  主体_天地 --- 人物_仲尼
  人物_仲尼 --- 概念_不知
  人物_仲尼 --- 生物_朝菌
  人物_仲尼 --- 境界_至人
  主体_鬼神 --- 人物_仲尼
  主体_天下 --- 人物_仲尼
  人物_仲尼 --- 人物_儒者
  人物_仲尼 --- 境界_不能
  人物_仲尼 --- 生物_彭祖
  人物_仲尼 --- 概念_自然
  人物_墨者 --- 境界_得道
  人物_墨者 --- 境界_真人
  人物_墨者 --- 人物_老子
  主体_天地 --- 人物_墨者
  人物_墨者 --- 概念_不知
  主体_鬼神 --- 人物_墨者
  主体_天下 --- 人物_墨者
  人物_儒者 --- 人物_墨者
  人物_墨者 --- 境界_不能
  人物_墨者 --- 生物_彭祖
  人物_墨者 --- 概念_自然
  人物_武王 --- 境界_得道
  人物_武王 --- 人物_老子
  主体_天地 --- 人物_武王
  人物_武王 --- 概念_不知
  人物_武王 --- 生物_朝菌
  主体_鬼神 --- 人物_武王
  主体_天下 --- 人物_武王
  人物_武王 --- 境界_不能
  人物_武王 --- 生物_彭祖
  人物_武王 --- 概念_自然
  境界_得道 --- 境界_有名
  境界_得道 --- 境界_真人
  人物_老子 --- 境界_得道
  人物_周公 --- 境界_得道
  境界_得道 --- 概念_五行
  人物_孔子 --- 境界_得道
  主体_天地 --- 境界_得道
  境界_得道 --- 概念_不知
  境界_得道 --- 生物_朝菌
  境界_得道 --- 境界_至人
  境界_得道 --- 概念_四方
  境界_得道 --- 概念_有待
  主体_鬼神 --- 境界_得道
  主体_天下 --- 境界_得道
  境界_得道 --- 概念_大道
  人物_儒者 --- 境界_得道
  境界_不能 --- 境界_得道
  境界_得道 --- 生物_彭祖
  境界_得道 --- 概念_自然
  境界_有名 --- 境界_真人
  人物_老子 --- 境界_有名
  主体_天地 --- 境界_有名
  境界_有名 --- 概念_不知
  境界_有名 --- 概念_四方
  主体_鬼神 --- 境界_有名
  主体_天下 --- 境界_有名
  境界_不能 --- 境界_有名
  境界_有名 --- 概念_自然
  人物_老子 --- 境界_真人
  人物_周公 --- 境界_真人
  主体_天地 --- 境界_真人
  境界_真人 --- 概念_不知
  境界_真人 --- 生物_朝菌
  境界_真人 --- 境界_至人
  境界_真人 --- 概念_四方
  境界_真人 --- 概念_有待
  主体_鬼神 --- 境界_真人
  主体_天下 --- 境界_真人
  人物_儒者 --- 境界_真人
  境界_不能 --- 境界_真人
  境界_真人 --- 生物_彭祖
  境界_真人 --- 概念_生死
  境界_真人 --- 概念_自然
  人物_周公 --- 人物_老子
  人物_老子 --- 概念_五行
  人物_孔子 --- 人物_老子
  主体_天地 --- 人物_老子
  人物_老子 --- 概念_不知
  人物_老子 --- 生物_朝菌
  人物_老子 --- 概念_四方
  人物_老子 --- 概念_有待
  主体_鬼神 --- 人物_老子
  主体_天下 --- 人物_老子
  人物_儒者 --- 人物_老子
  人物_老子 --- 境界_不能
  人物_老子 --- 生物_彭祖
  人物_老子 --- 概念_自然
  主体_天地 --- 人物_周公
  人物_周公 --- 概念_不知
  人物_周公 --- 生物_朝菌
  人物_周公 --- 境界_至人
  人物_周公 --- 概念_四方
  主体_鬼神 --- 人物_周公
  主体_天下 --- 人物_周公
  人物_儒者 --- 人物_周公
  人物_周公 --- 境界_不能
  人物_周公 --- 概念_自然
  主体_天地 --- 概念_五行
  概念_不知 --- 概念_五行
  概念_五行 --- 概念_四方
  主体_天下 --- 概念_五行
  境界_不能 --- 概念_五行
  概念_五行 --- 生物_彭祖
  概念_五行 --- 概念_自然
  主体_天地 --- 人物_孔子
  人物_孔子 --- 概念_不知
  主体_天下 --- 人物_孔子
  人物_孔子 --- 境界_不能
  人物_孔子 --- 概念_自然
  主体_天地 --- 概念_不知
  主体_天地 --- 生物_朝菌
  主体_天地 --- 境界_至人
  主体_天地 --- 概念_四方
  主体_天地 --- 概念_有待
  主体_天地 --- 主体_鬼神
  主体_天下 --- 主体_天地
  主体_天地 --- 概念_大道
  主体_天地 --- 人物_儒者
  主体_天地 --- 境界_不能
  主体_天地 --- 生物_彭祖
  主体_天地 --- 概念_生死
  主体_天地 --- 概念_自然
  概念_不知 --- 生物_朝菌
  境界_至人 --- 概念_不知
  概念_不知 --- 概念_四方
  概念_不知 --- 概念_有待
  主体_鬼神 --- 概念_不知
  主体_天下 --- 概念_不知
  概念_不知 --- 概念_大道
  人物_儒者 --- 概念_不知
  境界_不能 --- 概念_不知
  概念_不知 --- 概念_物化
  概念_不知 --- 生物_彭祖
  概念_不知 --- 概念_生死
  概念_不知 --- 概念_自然
  境界_至人 --- 生物_朝菌
  主体_鬼神 --- 生物_朝菌
  主体_天下 --- 生物_朝菌
  人物_儒者 --- 生物_朝菌
  境界_不能 --- 生物_朝菌
  生物_彭祖 --- 生物_朝菌
  概念_自然 --- 生物_朝菌
  主体_鬼神 --- 境界_至人
  主体_天下 --- 境界_至人
  人物_儒者 --- 境界_至人
  境界_不能 --- 境界_至人
  境界_至人 --- 概念_物化
  境界_至人 --- 生物_彭祖
  境界_至人 --- 概念_自然
  主体_鬼神 --- 概念_四方
  主体_天下 --- 概念_四方
  概念_四方 --- 概念_大道
  境界_不能 --- 概念_四方
  概念_四方 --- 概念_自然
  主体_天下 --- 概念_有待
  境界_不能 --- 概念_有待
  概念_有待 --- 生物_彭祖
  概念_有待 --- 概念_自然
  主体_天下 --- 主体_鬼神
  主体_鬼神 --- 概念_大道
  主体_鬼神 --- 人物_儒者
  主体_鬼神 --- 境界_不能
  主体_鬼神 --- 生物_彭祖
  主体_鬼神 --- 概念_生死
  主体_鬼神 --- 概念_自然
  主体_天下 --- 概念_大道
  主体_天下 --- 人物_儒者
  主体_天下 --- 境界_不能
  主体_天下 --- 生物_彭祖
  主体_天下 --- 概念_生死
  主体_天下 --- 概念_自然
  境界_不能 --- 概念_大道
  概念_大道 --- 概念_自然
  人物_儒者 --- 境界_不能
  人物_儒者 --- 生物_彭祖
  人物_儒者 --- 概念_自然
  境界_不能 --- 概念_物化
  境界_不能 --- 生物_彭祖
  境界_不能 --- 概念_生死
  境界_不能 --- 概念_自然
  概念_物化 --- 概念_自然
  概念_生死 --- 生物_彭祖
  概念_自然 --- 生物_彭祖
