graph LR
classDef person fill:#f9f,stroke:#333,stroke-width:2px;
classDef place fill:#ccf,stroke:#333,stroke-width:2px;
classDef bio fill:#cfc,stroke:#333,stroke-width:2px;
classDef concept fill:#fcf,stroke:#333,stroke-width:2px;
classDef state fill:#ffc,stroke:#333,stroke-width:2px;
classDef metaphor fill:#cff,stroke:#333,stroke-width:2px;
classDef subject fill:#fdd,stroke:#333,stroke-width:2px;
classDef duality fill:#ddd,stroke:#333,stroke-width:2px;
  主体_天地(天地)
  class 主体_天地 subject;
  概念_自然(自然)
  class 概念_自然 concept;
  主体_圣人(圣人)
  class 主体_圣人 subject;
  概念_三才(三才)
  class 概念_三才 concept;
  概念_不知(不知)
  class 概念_不知 concept;
  主体_天下(天下)
  class 主体_天下 subject;
  境界_不能(不能)
  class 境界_不能 state;
